[application]
android_manifest = "android/AndroidManifest.xml"
android_main_activity = "android/MainActivity.kt"

[android]
gradle_dependencies = [
    "androidx.media3:media3-exoplayer:1.4.1",
    "androidx.media3:media3-session:1.4.1",
]

[web.app]

# HTML title tag content
title = "doyou"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
